server:
  port: 8081
security:
  oauth2:
    client:
      clientId: barClientIdPassword
      clientSecret: secret
      accessTokenUri: http://127.0.0.1:8080/oauth/token
      userAuthorizationUri: http://127.0.0.1:8080/oauth/authorize
      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: http://127.0.0.1:8080/user
    resource:
      id: AUTH_RESOURCE
      userInfoUri: http://127.0.0.1:8080/user
      prefer-token-info: false
    authorization:
      check-token-access: http://127.0.0.1:8080/oauth/check_token